### ISSUE TITLE
Using the argument "--socket=wayland" breaks the app.

### ISSUE THREAD

**Issue by Ratevandr** [flathub/com.ultimaker.cura#17]
When an argument is used "--socket=wayland" the application after launch shows only a transparent window.  When using only --socket=x11 in a wayland session, everything works fine.
OS: KDE Neon (based on ubuntu 22.04)
GPU: Nvidia 3060
KDE: 5.27
Qt: 5.15.8

**Comment by Tim453** [comment]
Does it work in the AppImage Version?

**Comment by Ratevandr** [comment]
> Does it work in the AppImage Version?

AppImage only works with `QT_QPA_PLATFORM=xcb`
i.e.
`QT_QPA_PLATFORM=xcb UltiMaker-Cura-5.2.2-linux-modern.AppImage`
