### ISSUE TITLE
Broken on Wayland

### ISSUE THREAD

**Issue by Unrud** [flathub/com.ultimaker.cura#19]
Qt gets forced to use X11 by this environment variable:

https://github.com/flathub/com.ultimaker.cura/blob/c1cd86baa40efd2fb25eab077f0788d7faf5ca76/com.ultimaker.cura.yml#L20-L21

But the X11 socket is not available when using Wayland:

https://github.com/flathub/com.ultimaker.cura/blob/c1cd86baa40efd2fb25eab077f0788d7faf5ca76/com.ultimaker.cura.yml#L8

If you want to prefer XWayland over Wayland remove `--socket=fallback-x11` and set `--env=QT_QPA_PLATFORM=xcb;wayland`.

**Comment by Tim453** [comment]
Thanks for the advice. Why should `--socket=fallback-x11` be removed? I think if I remove it, it won't work under X11 sessions anymore.

**Comment by neildarlow** [comment]
Setting the QT_QPA_PLATFORM variable to "wayland" allows Cura to start.

**Comment by Unrud** [comment]
> Why should `--socket=fallback-x11` be removed? I think if I remove it, it won't work under X11 sessions anymore.

Right. I didn't notice that the argument `--socket=x11` was not present.

**Comment by Tim453** [comment]
Do we need any of these variables? I tried it in an Ubuntu Wayland session and it worked for me without any environment variables. But in #17 someone mentioned that it is only showing a transparent window.

**Comment by Unrud** [comment]
> I tried it in an Ubuntu Wayland session and it worked for me without any environment variables.

I notice some minor issues on wayland:

* Windows don't have shadows
* Open/Save/Export dialogs are opened in the background and not modal
* Text of disabled menu entries is not gray but transparent (you can see other other windows / desktop background through the text :eyes:)

**Comment by kurtabersold** [comment]
>Open/Save/Export dialogs are opened in the background

Found this issue searching for a solution for this behavior. I am using Gnome+Wayland+Nvidia Optimus.
