### ISSUE TITLE
Warning: Update to many dependencies in Cura 5.0

### ISSUE THREAD

**Issue by Ghostkeeper** [flathub/com.ultimaker.cura#3]
With the upcoming Cura release 5.0, Cura will be updating its Python version to 3.10.0 and Qt to version 6.2. We're packaging the new versions inside of the AppImage.

This update is necessary to support the new MacOS versions. It is not necessary to continue supporting Linux, so it's not really a problem here. However this update means that some code will eventually be written that only works in the newest versions of these dependencies. These are the major dependencies that we're updating that might be relevant to this repository:

- Qt and PyQt are updated to version 6.2.0. This means code breakage: It's importing PyQt6 everywhere, so PyQt6 needs to be available instead of PyQt5.
- Python is updated to 3.10.0. For the moment, it's kept backwards compatible with at least Python 3.9 (which is the one used here, looking at the patches made). No guarantees for the future though, so you might want to update the Python version and  [references to 3.9](https://github.com/flathub/com.ultimaker.cura/blob/f5d0beb01429517dac2f87aa364e4c835c590aa5/com.ultimaker.cura.yml#L70).
- Sip is updated to 6.5.0. This is a really big change in the way we build the Python bindings for some C++ libraries Cura uses. Externally though, not a whole lot should change. In theory, CMake should just build it from scratch, as long as Sip 6.5 is available.
- Shapely (the Python package) is replaced by Pyclipper (because until very recently they didn't support Python 3.10 yet on MacOS). This itself is not a difficult change, just a different package to request from Pip. However it also drops the need for Geos. Geos is no longer a dependency. This probably speeds up your build a bit.
- Many Python packages have been updated. This is necessary to support Python 3.10.

As of this writing, we're still having some trouble packaging the MacOS image with the updated Sip version, but these changes are likely to remain stable at this point.

**Comment by thopiekar** [comment]
Have fun: https://thopiekar.eu/2022/06/21/cura-rolled-out-as-flatpak/

**Comment by jellespijker** [comment]
Also take note of this PR https://github.com/Ultimaker/Cura/pull/12708
Which is a complete switch in our build process.

Switching to Conan as our dependency manager opens up a possibility for flat pack maintainers imo. 

See https://docs.conan.io/en/1.44/integrations/deployment/flatpak.html

We could add (or merge a PR) in our GitHub repo https:/github.com/ultimaker/conan-config for a specific FlatPack generator.
