### ISSUE TITLE
Flatpak Cura not running on Elementary OS

### ISSUE THREAD

**Issue by doobes** [flathub/com.ultimaker.cura#32]
I installed Cura yesterday on an Elementary OS 7.1 box and when attempting to start, I get the big blue logo, then it dissapears and it spits back in the terminal:

PyInstaller/loader/pyimod02_importers.py:352: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module’s documentation for alternative uses
QApplication: invalid style override ‘adwaita’ passed, ignoring it.
Available styles: Windows, Fusion
Fontconfig warning: “/etc/fonts/conf.d/05-flatpak-fontpath.conf”, line 5: unknown element “reset-dirs”
Fontconfig error: “/etc/fonts/conf.d/05-flatpak-fontpath.conf”, line 6: invalid attribute ‘salt’
Fontconfig error: “/etc/fonts/conf.d/05-flatpak-fontpath.conf”, line 7: invalid attribute ‘salt’
Fontconfig warning: “/run/host/font-dirs.xml”, line 4: unknown element “remap-dir”
Fontconfig error: “/run/host/font-dirs.xml”, line 4: invalid attribute ‘as-path’
Fontconfig warning: “/run/host/font-dirs.xml”, line 5: unknown element “remap-dir”
Fontconfig error: “/run/host/font-dirs.xml”, line 5: invalid attribute ‘as-path’
Fontconfig error: Cannot load config file from /run/host/font-dirs.xml
Fontconfig warning: “/etc/fonts/conf.avail/05-reset-dirs-sample.conf”, line 6: unknown element “reset-dirs”
QQmlApplicationEngine failed to load component
QQmlComponent: Component is not ready

I’m not the most Linux centric person in the whole world.

Any thoughts on what this is trying to tell me?

Thank you

chris

**Comment by Tim453** [comment]
Hello, can you try to run `unset QT_STYLE_OVERRIDE` before starting Cura?

**Comment by doobes** [comment]
Interesting.

It runs from the command line via flatpak run com.ultimaker.cura, but doesn't run when clicking on the icon in the applications window or running from the app center.

Thanks!

**Comment by doobes** [comment]
When run from the command line I get this:

PyInstaller/loader/pyimod02_importers.py:352: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
Fontconfig warning: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 5: unknown element "reset-dirs"
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 6: invalid attribute 'salt'
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 7: invalid attribute 'salt'
Fontconfig warning: "/run/host/font-dirs.xml", line 4: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 4: invalid attribute 'as-path'
Fontconfig warning: "/run/host/font-dirs.xml", line 5: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 5: invalid attribute 'as-path'
Fontconfig error: Cannot load config file from /run/host/font-dirs.xml
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Cyclic dependency detected between "file:///app/cura/share/cura/resources/qml/Actions.qml" and "file:///app/cura/share/cura/resources/qml/Actions.qml"

Looking around, 05-flatpak-fontpath.conf, font-dirs.xml and 05-reset-dirs-sample.conf are non-existent.

chris

**Comment by Tim453** [comment]
These warnings and fontconfig errors are normal. I added `unset QT_STYLE_OVERRIDE` to the  to the start script. Please try to install the test build from [here](https://github.com/flathub/com.ultimaker.cura/pull/33) and check if it can start now.

**Comment by doobes** [comment]
Um,

Sorry to have disappeared.

How do I go about installing the test build?

Thank you
