### ISSUE TITLE
Unable to Run Ultimaker Cura on ChromeOSFlex

### ISSUE THREAD

**Issue by kafufafu** [flathub/com.ultimaker.cura#36]
After a successful installation, I am unable to execute Ultimaker Cura. When I try to run it in the terminal, I receive the following information:

ChromeOsFlex Versión 123.0.6312.132 (Build oficial) (64 bits)
----------------------------------------------------------------------------------------------------------------------------------------------------

kazukimafufafu@penguin:~$ flatpak install flathub com.ultimaker.cura
Looking for matches…

com.ultimaker.cura permissions:
    ipc       network       wayland      x11      devices      file access [1]      system dbus access [2]

    [1] /media, /run/media, home
    [2] org.freedesktop.UDisks2

        ID                          Branch         Op         Remote          Download
 1. [✓] com.ultimaker.cura          stable         i          flathub         350.8 MB / 400.0 MB

Installation complete.
kazukimafufafu@penguin:~$ flatpak run com.ultimaker.cura
Fontconfig warning: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 5: unknown element "reset-dirs"
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 6: invalid attribute 'salt'
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 7: invalid attribute 'salt'
Fontconfig warning: "/run/host/font-dirs.xml", line 4: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 4: invalid attribute 'as-path'
Fontconfig warning: "/run/host/font-dirs.xml", line 5: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 5: invalid attribute 'as-path'
Fontconfig error: Cannot load config file from /run/host/font-dirs.xml
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
qt.qpa.wayland: Ignoring unexpected wl_surface.enter received for output with id: 7 screen name: "Screen5" screen model: "unknown" This is most likely a bug in the compositor.
qt.qml.typeresolution.cycle: Cyclic dependency detected between "file:///app/cura/share/cura/resources/qml/Actions.qml" and "file:///app/cura/share/cura/resources/qml/Actions.qml"
The Wayland connection broke. Did the Wayland compositor die?

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Could you please provide assistance in resolving this issue? 
Thank you for your help and assistance with this matter!

**Comment by Tim453** [comment]
Does the official AppImage work?
[Here](https://github.com/Ultimaker/Cura/issues/18818) someone else had the same problem.

**Comment by kafufafu** [comment]
> Does the official AppImage work? [Here](https://github.com/Ultimaker/Cura/issues/18818) someone else had the same problem.

yes, official appimage work (5.6.0).

---------------------------------------------------------

Uninstalling and Reinstalling Linux Environment, Next Steps:

After executing the following commands:

--------------------------------------------------
sudo apt install fuse
sudo apt install flatpak
flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
---------------------------------------------------
//(I restarted 'penguin')

---------------------------------------------------
flatpak install flathub com.ultimaker.cura
------------------------------------------------------------
//(Version 5.7.0 installed)

-------------------------------------------------------------

flatpak run com.ultimaker.cura
------------------------------------------------------------
>(The same error occurred when attempting to start it)

// Downloaded the official appimage

-------------------------------------------------------------
chmod +x UltiMaker-Cura-5.6.0-linux-X64.AppImage     //saved in Linux directory
./UltiMaker-Cura-5.6.0-linux-X64.AppImage                     //app start normally

**Comment by Tim453** [comment]
Can you also try if the 5.7.0 AppImage works?

**Comment by Farroner1** [comment]
>I have tested the following .AppImage versions:

Version 5.6.0 (starts correctly).
Version 5.7.0 (fails to start).
Version 5.7.1 (fails to start).

Exactly the same behavior on a Chromebook with Debian 12 (Bookwork).
5.6.0 runs, the newer versions do not
>

**Comment by kafufafu** [comment]
@Farroner1 

1) I finally ended up using Ubuntu and version 4.13.2 available from the app store. I'm increasingly convinced that it's a problem in the source code and opted to stop trying after breaking the system multiple times lol.

2) The current status of Ultimaker Cura 5.7.1 is: it doesn't work on most Linux distros and doesn't work on some computers with Windows 11.
