### ISSUE TITLE
Cura takes a LOOOOOOOONG time to open/load a file

### ISSUE THREAD

**Issue by thepragmaticmero** [flathub/com.ultimaker.cura#42]
check the time lol.
- Click on "open"
[Kooha-2024-09-06-14-24-35 (online-video-cutter.com).webm](https://github.com/user-attachments/assets/341e1250-2b88-4957-8c03-03ab3c1b9161)
- Time it actually opens
[Kooha-2024-09-06-14-24-35.webm](https://github.com/user-attachments/assets/f2c15322-634e-424f-a81a-60ec7337c2e9)
It doesn't happen with the .AppImage

- Fedora Silverblue 41 (It happens too on workstation and silverblue 40)

**Comment by Tim453** [comment]
Disabling USB Printing maybe fixes this problem: https://github.com/Ultimaker/Cura/issues/16249#issuecomment-2094405826

**Comment by thepragmaticmero** [comment]
Sometimes computing is black magic, yep, nice workaround, It works as expected now.
