### ISSUE TITLE
Cura does not start

### ISSUE THREAD

**Issue by daved09** [flathub/com.ultimaker.cura#7]
The Cura Vesion 5.1.1 does not start on Ubuntu.

Here is the Terminal Output:

> flatpak run com.ultimaker.cura 
PyInstaller/loader/pyimod02_importers.py:499: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
Gtk-Message: 12:37:28.477: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:37:28.478: Failed to load module "canberra-gtk-module"
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
QQmlApplicationEngine failed to load component
QQmlComponent: Component is not ready
QQmlComponent: Component is not ready
QQmlComponent: Component is not ready

**Comment by Tim453** [comment]
Which Ubuntu version are you using?

**Comment by daved09** [comment]
I´m using Zorin OS 16.1 based on Ubuntu 20.04.
